login:
   path: /login
   controller: App\Controller\LoginController::login

signup:
  path: /signup
  controller: App\Controller\SignupController::signup

profil-entreprise:
   path: /profil-entreprise/{id}
   controller: App\Controller\ProfilEntrepriseController::displayProfilEntreprise

profil-candidat:
   path: /profil-candidat/{id}
   controller: App\Controller\ProfilCandidatController::displayProfilCandidat

profil-utilisateur:
   path: /profil-utilisateur
   controller: App\Controller\ProfilUtilisateurController::displayProfilUtilisateur

liste-entreprise:
   path: /liste-entreprise
   controller: App\Controller\ListeEntrepriseController::displayListeEntreprise

liste-matchs:
   path: /liste-matchs
   controller: App\Controller\ListeMatchsController::displayListeMatchs

liste-offres:
   path: /liste-offres
   controller: App\Controller\ListeOffresController::displayListeOffres

liste-candidatures:
   path: /liste-candidatures
   controller: App\Controller\ListeCandidaturesController::displayListeCandidatures

liste-conversations:
   path: /liste-conversations
   controller: App\Controller\ListeConversationsController::displayListeConversations

conversation:
   path: /conversation/{id}
   controller: App\Controller\ConversationController::displayConversation

home:
   path: /home
   controller: App\Controller\HomeController::displayHome

recherche:
   path: /recherche
   controller: App\Controller\RechercheController::displayRecherche

offre:
   path: /offre/{id}
   controller: App\Controller\OffreController::displayOffre


inscription:
   path: /inscription
   controller: App\Controller\HomeController::inscription

auth:
   path: /
   controller: App\Controller\AuthController::displayAuth

accueil:
   path: '/accueil'
   controller: App\Controller\HomeController::accueil

search:
   path: '/search'
   controller: App\Controller\RechercheController::search

create:
   path: '/create'
   controller: App\Controller\CreateAnnonceController::displayForm


post-annonce:
   path: '/post-annonce'
   controller: App\Controller\CreateAnnonceController::postForm

update-profil:
   path: '/update-profil'
   controller: App\Controller\ProfilUtilisateurController::updateInfos


notifications:
   path: '/notifications'
   controller: App\Controller\NotificationsController::displayPage

   
mes-offres:
   path: '/mes-offres'
   controller: App\Controller\MesOffresController::displayListeOffres


delete-annonce:
   path: '/delete-annonce/{id}'
   controller: App\Controller\MesOffresController::deleteOffre



postuler:
   path: /postuler/{id}
   controller: App\Controller\OffreController::postuler


accepter:
   path: /accepter/{id}/{offre_id}
   controller: App\Controller\OffreController::accepter


refuser:
   path: /refuser/{id}
   controller: App\Controller\OffreController::refuser